/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

/**
 *
 * @author nikko
 */
public class DecimalFrame extends javax.swing.JFrame {

    /**
     * Creates new form DecimalFrame
     */
    public DecimalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewField = new javax.swing.JTextField();
        ChangeSign = new javax.swing.JButton();
        BackSpace = new javax.swing.JButton();
        ClearEntry = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Plus = new javax.swing.JButton();
        Number7 = new javax.swing.JButton();
        Number8 = new javax.swing.JButton();
        Number9 = new javax.swing.JButton();
        Minus = new javax.swing.JButton();
        Number4 = new javax.swing.JButton();
        Number5 = new javax.swing.JButton();
        Number6 = new javax.swing.JButton();
        Number3 = new javax.swing.JButton();
        Multiply = new javax.swing.JButton();
        Number2 = new javax.swing.JButton();
        Number1 = new javax.swing.JButton();
        Equal = new javax.swing.JButton();
        Divide = new javax.swing.JButton();
        Period = new javax.swing.JButton();
        Number0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(440, 650));
        setPreferredSize(new java.awt.Dimension(440, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ViewField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ViewField.setText("12232");
        getContentPane().add(ViewField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 340, 58));

        ChangeSign.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ChangeSign.setText("±");
        ChangeSign.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(ChangeSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        BackSpace.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BackSpace.setText("←");
        BackSpace.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(BackSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        ClearEntry.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ClearEntry.setText("CE");
        ClearEntry.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(ClearEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        Clear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Clear.setText("C");
        Clear.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        Plus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Plus.setText("+");
        Plus.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        Number7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Number7.setText("7");
        Number7.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Number7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        Number8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Number8.setText("8");
        Number8.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Number8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        Number9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Number9.setText("9");
        Number9.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Number9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        Minus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Minus.setText("-");
        Minus.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        Number4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Number4.setText("4");
        Number4.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Number4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        Number5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Number5.setText("5");
        Number5.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Number5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        Number6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Number6.setText("6");
        Number6.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Number6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        Number3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Number3.setText("3");
        Number3.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Number3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        Multiply.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Multiply.setText("*");
        Multiply.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Multiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        Number2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Number2.setText("2");
        Number2.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Number2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        Number1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Number1.setText("1");
        Number1.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        Equal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Equal.setText("=");
        Equal.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        Divide.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Divide.setText("/");
        Divide.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Divide, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));

        Period.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Period.setText(".");
        Period.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Period, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, -1));

        Number0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Number0.setText("0");
        Number0.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(Number0, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DecimalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DecimalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DecimalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DecimalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DecimalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackSpace;
    private javax.swing.JButton ChangeSign;
    private javax.swing.JButton Clear;
    private javax.swing.JButton ClearEntry;
    private javax.swing.JButton Divide;
    private javax.swing.JButton Equal;
    private javax.swing.JButton Minus;
    private javax.swing.JButton Multiply;
    private javax.swing.JButton Number0;
    private javax.swing.JButton Number1;
    private javax.swing.JButton Number2;
    private javax.swing.JButton Number3;
    private javax.swing.JButton Number4;
    private javax.swing.JButton Number5;
    private javax.swing.JButton Number6;
    private javax.swing.JButton Number7;
    private javax.swing.JButton Number8;
    private javax.swing.JButton Number9;
    private javax.swing.JButton Period;
    private javax.swing.JButton Plus;
    private javax.swing.JTextField ViewField;
    // End of variables declaration//GEN-END:variables
}
